-- ====================================================================
-- SKRIP SETUP DATABASE SUPABASE REALTIME - BUKU TAMU & KOMENTAR d1kyra
-- ====================================================================
-- Cara pakai:
-- 1. Buka dashboard Supabase (https://supabase.com/dashboard)
-- 2. Pilih Project Anda -> Klik menu "SQL Editor" di bilah samping kiri
-- 3. Buat "New Query", paste seluruh isi skrip ini, lalu klik "Run"
-- ====================================================================

-- 1. Buat tabel comments jika belum ada
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    comment TEXT NOT NULL,
    likes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 3. Hapus policy lama jika pernah dibuat (agar tidak duplikat)
DROP POLICY IF EXISTS "Allow public select comments" ON public.comments;
DROP POLICY IF EXISTS "Allow public insert comments" ON public.comments;
DROP POLICY IF EXISTS "Allow public update likes" ON public.comments;
DROP POLICY IF EXISTS "Allow public delete comments" ON public.comments;

-- 4. Buat Kebijakan Akses (RLS Policies)
-- Izinkan semua pengunjung membaca komentar
CREATE POLICY "Allow public select comments"
ON public.comments
FOR SELECT
TO public
USING (true);

-- Izinkan semua pengunjung mengirim komentar baru
CREATE POLICY "Allow public insert comments"
ON public.comments
FOR INSERT
TO public
WITH CHECK (true);

-- Izinkan pengunjung menambah Like
CREATE POLICY "Allow public update likes"
ON public.comments
FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

-- Izinkan penghapusan komentar (admin)
CREATE POLICY "Allow public delete comments"
ON public.comments
FOR DELETE
TO public
USING (true);

-- 5. Aktifkan Realtime Publication
-- Supaya jika ada yang komen di HP, laptop orang lain langsung muncul otomatis!
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'comments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.comments;
  END IF;
END $$;
